language: swift # or objective-c
osx_image: xcode12.5
script:
  - xcodebuild -scheme Onecalios -workspace Onecalios.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.5' build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -t adaeb29b-cb7b-4842-b1ad-5652571ce76e
